import assert from 'node:assert/strict';
import fs from 'node:fs';
import ts from 'typescript';
const source=fs.readFileSync(new URL('../app/game.ts',import.meta.url),'utf8');
const compiled=ts.transpileModule(source,{compilerOptions:{module:ts.ModuleKind.ESNext,target:ts.ScriptTarget.ES2022}}).outputText;
const storage=new Map();globalThis.localStorage={getItem:k=>storage.get(k)||null,setItem:(k,v)=>storage.set(k,v)};
const noop=()=>{};globalThis.window={devicePixelRatio:1,addEventListener:noop,removeEventListener:noop};globalThis.document={hidden:false,addEventListener:noop,removeEventListener:noop};
globalThis.Image=class {complete=false;naturalWidth=0;set src(v){queueMicrotask(()=>this.onload?.())}};
globalThis.ResizeObserver=class{observe(){}disconnect(){}};globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=noop;
let registered;document.modelContext={registerTool:async(t)=>{registered=t}};
const gradient={addColorStop:noop};const context=new Proxy({measureText:()=>({width:100}),createLinearGradient:()=>gradient,createRadialGradient:()=>gradient},{get:(o,k)=>o[k]||noop,set:(o,k,v)=>{o[k]=v;return true}});
const {Game}=await import('data:text/javascript;base64,'+Buffer.from(compiled).toString('base64'));
const game=new Game({getContext:()=>context,getBoundingClientRect:()=>({width:1440,height:810})},noop);await game.ready;
const run=(seconds)=>{for(let i=0;i<Math.round(seconds*120);i++){game.elapsed+=1/120;game.update(1/120)}};
const tap=k=>{game.input(k,true);run(1/120);game.input(k,false)};
const place=(room,x,y=705)=>{game.state.room=room;game.state.roomName=game.world[room].name;game.player={x,y,vx:0,vy:0,face:1,grounded:true};game.coyote=.12;game.invincible=0;game.dashCooldown=0;game.dashTime=0;game.usedDouble=false;game.keys.clear();game.pressed.clear()};
let tests=0;function check(name,fn){fn();console.log('PASS',name);tests++}
game.start();
check('First jump reaches the 145px ability ledge',()=>{place(2,890);game.input('Space',true);let min=705;for(let i=0;i<90;i++){run(1/120);min=Math.min(min,game.player.y)}game.input('Space',false);assert.ok(min<560,`jump apex ${min} must be <560`)});
check('Single jump crosses the first gap without damage',()=>{place(0,810);game.input('ArrowRight',true);run(.15);game.input('Space',true);run(.9);game.input('Space',false);game.input('ArrowRight',false);run(.2);assert.ok(game.player.x>1070);assert.equal(game.player.y,705);assert.equal(game.state.health,5)});
check('Sun Dash is acquired through proximity',()=>{place(1,1940);run(.03);assert.equal(game.state.dash,true)});
check('Amber barrier stops walking',()=>{place(2,540);game.input('ArrowRight',true);run(.6);game.input('ArrowRight',false);assert.ok(game.player.x<590);assert.equal(game.broken.has(2),false)});
check('Sun Dash breaks the barrier and crosses it',()=>{place(2,555);game.input('ArrowRight',true);tap('ShiftLeft');run(.18);game.input('ArrowRight',false);assert.equal(game.broken.has(2),true);assert.ok(game.player.x>635)});
check('Sky Feather can be acquired by a real jump from the ground',()=>{place(2,910);game.input('Space',true);run(.65);game.input('Space',false);assert.equal(game.state.doubleJump,true)});
check('Double jump grants extra height and cannot be spammed',()=>{place(0,300);game.input('Space',true);run(.3);game.input('Space',false);run(.02);game.input('Space',true);run(.03);assert.ok(game.player.vy<-500);assert.equal(game.usedDouble,true);game.input('Space',false);run(.05);const velocity=game.player.vy;tap('Space');assert.ok(game.player.vy>velocity);game.keys.clear()});
check('Ability gate denies entry before unlock',()=>{place(1,1310,340);game.state.doubleJump=false;tap('KeyE');assert.equal(game.state.room,1);game.state.doubleJump=true;tap('KeyE');assert.equal(game.state.room,3)});
check('Combat defeats a wisp and yields light',()=>{place(0,1500);const e=game.world[0].enemies[0];e.x=1550;e.home=1550;e.range=0;e.y=660;const light=game.state.light;tap('KeyJ');run(.33);tap('KeyJ');assert.equal(e.hp,0);assert.ok(game.state.light>=light+3)});
check('Damage has an invulnerability grace period',()=>{place(0,2000);game.hurt(false);const hp=game.state.health;game.hurt(false);assert.equal(game.state.health,hp)});
check('All three sunseeds and final restoration are completable',()=>{for(const room of [2,4,5]){for(const e of game.world[room].enemies)e.hp=0;const seed=game.world[room].seed;place(room,seed.x,seed.y+35);run(.02)}assert.deepEqual([...game.state.seeds].sort(),[2,4,5]);place(0,230);tap('KeyE');assert.equal(game.state.won,true);assert.equal(game.state.health,5)});
check('Save and resume preserve abilities, sunseeds, and checkpoint',()=>{game.save();assert.equal(game.hasSave(),true);game.start(true);assert.equal(game.state.dash,true);assert.equal(game.state.doubleJump,true);assert.equal(game.state.seeds.length,3);assert.equal(game.state.room,0);assert.equal(game.player.x,230)});
check('Malformed local save is safely ignored',()=>{storage.set('luma-sunseed-v1','{oops');assert.equal(game.hasSave(),false);game.start(true);assert.equal(game.state.room,0);assert.equal(game.state.seeds.length,0)});
check('Read-only progress tool validates inputs',()=>{assert.equal(registered.name,'read_luma_progress');assert.equal(registered.execute({}).room,0);assert.throws(()=>registered.execute({room:5}));assert.equal(game.state.room,0)});
game.destroy();console.log(`\n${tests} gameplay checks passed.`);
