/** Luma's deterministic, fixed-step TypeScript game engine. No remote services. */
export interface Snapshot {room:number;roomName:string;health:number;light:number;seeds:number[];dash:boolean;doubleJump:boolean;visited:number[];time:number;won:boolean;message:string}
type Platform={x:number;y:number;w:number;h:number};
type Door={x:number;y:number;to:number;label:string;needs?:'doubleJump'|'dash'};
type Mote={x:number;y:number;id:string};
type Enemy={x:number;y:number;home:number;range:number;phase:number;hp:number;hit:number};
type Particle={x:number;y:number;vx:number;vy:number;life:number;max:number;color:string;r:number};
type Room={name:string;tint:string;platforms:Platform[];doors:Door[];enemies:Enemy[];motes:Mote[];shrine?:number;seed?:{x:number;y:number};ability?:{x:number;y:number;type:'dash'|'doubleJump'}};
const W=2400,H=810,SAVE_KEY='luma-sunseed-v1';
const rect=(x:number,y:number,w:number,h=55):Platform=>({x,y,w,h});
const ground=(x:number,w:number)=>rect(x,705,w,180);
const enemy=(x:number,y:number,range=120):Enemy=>({x,y,home:x,range,phase:x/100,hp:2,hit:0});
function rooms():Room[]{
 const r:Room[]=[
  {name:'The Waking Glade',tint:'#adcf6105',platforms:[ground(0,900),ground(1070,1330),rect(450,575,240),rect(770,455,210),rect(1230,565,240),rect(1710,550,240)],doors:[{x:2310,y:705,to:1,label:'Whisper Falls'}],enemies:[enemy(1550,662),enemy(2070,658,100)],motes:[],shrine:230},
  {name:'Whisper Falls',tint:'#29dce418',platforms:[ground(0,2400),rect(460,560,260),rect(830,460,220),rect(1170,340,280),rect(1730,560,240)],doors:[{x:85,y:705,to:0,label:'Waking Glade'},{x:2310,y:705,to:2,label:'Amber Hollow'},{x:1310,y:340,to:3,label:'Windborne Canopy',needs:'doubleJump'}],enemies:[enemy(900,665,150),enemy(1560,660,140)],motes:[],shrine:310,ability:{x:1940,y:665,type:'dash'}},
  {name:'Amber Hollow',tint:'#9f520b35',platforms:[ground(0,1020),ground(1210,1190),rect(790,560,230),rect(1220,540,200),rect(1570,405,260),rect(2040,480,250)],doors:[{x:85,y:705,to:1,label:'Whisper Falls'},{x:2170,y:480,to:5,label:'Sunspire Ruins',needs:'doubleJump'}],enemies:[enemy(1390,665),enemy(1970,656,150)],motes:[],shrine:1310,ability:{x:910,y:510,type:'doubleJump'},seed:{x:1700,y:355}},
  {name:'Windborne Canopy',tint:'#73ed8822',platforms:[ground(0,750),ground(970,630),ground(1820,580),rect(410,545,210),rect(800,430,260),rect(1270,530,240),rect(1620,390,270),rect(2070,540,210)],doors:[{x:85,y:705,to:4,label:'Moonpetal Sanctuary'},{x:1230,y:705,to:1,label:'Whisper Falls'},{x:2310,y:705,to:5,label:'Sunspire Ruins'}],enemies:[enemy(580,659),enemy(1390,485,110),enemy(2090,659)],motes:[],shrine:1140},
  {name:'Moonpetal Sanctuary',tint:'#6668d140',platforms:[ground(0,700),ground(920,780),ground(1900,500),rect(350,550,220),rect(760,400,240),rect(1160,260,300),rect(1650,445,230),rect(2060,570,230)],doors:[{x:2310,y:705,to:3,label:'Windborne Canopy'}],enemies:[enemy(450,509,80),enemy(1000,660,80),enemy(1340,215,95)],motes:[],shrine:2120,seed:{x:1300,y:205}},
  {name:'Sunspire Ruins',tint:'#e7a13320',platforms:[ground(0,900),ground(1110,1290),rect(470,565,260),rect(870,435,260),rect(1300,535,200),rect(1660,400,320),rect(2090,540,200)],doors:[{x:85,y:705,to:3,label:'Windborne Canopy'},{x:2210,y:705,to:2,label:'Amber Hollow'}],enemies:[enemy(650,521,110),enemy(1470,660,120),{...enemy(1840,345,120),hp:5}],motes:[],shrine:300,seed:{x:1830,y:335}}
 ];
 r.forEach((room,ri)=>{room.platforms.forEach((p,pi)=>{if(p.y<700){for(let i=0;i<3;i++)room.motes.push({x:p.x+45+i*(p.w-90)/2,y:p.y-38,id:`${ri}-${pi}-${i}`})}});for(let i=0;i<7;i++)room.motes.push({x:430+i*270,y:653,id:`${ri}-g-${i}`})});return r;
}
export class Game {
 ready:Promise<void>;state:Snapshot={room:0,roomName:'The Waking Glade',health:5,light:0,seeds:[],dash:false,doubleJump:false,visited:[0],time:0,won:false,message:''};
 private ctx:CanvasRenderingContext2D;private bg=new Image();private sprite=new Image();private world=rooms();private keys=new Set<string>();private pressed=new Set<string>();private collected=new Set<string>();private broken=new Set<number>();private particles:Particle[]=[];private paused=true;private started=false;private stopped=false;private raf=0;private last=0;private accumulator=0;private elapsed=0;private messageUntil=0;private camera=0;private viewport=1440;private scale=1;private checkpoint={room:0,x:230,y:705};private saveAvailable=true;private mute=false;private audio:AudioContext|null=null;private music=0;private nextNote=0;private invincible=0;private shake=0;private attack=0;private attackCooldown=0;private dashTime=0;private dashCooldown=0;private coyote=0;private jumpBuffer=0;private usedDouble=false;private transition=0;private lastPublish=0;private safe={x:230,y:705};private player={x:230,y:705,vx:0,vy:0,face:1,grounded:true};private resize:ResizeObserver;private lifecycle=new AbortController();private ambient:Array<{x:number;y:number;s:number;phase:number}>=[];
 constructor(private canvas:HTMLCanvasElement,private onUpdate:(s:Snapshot)=>void){
  this.ctx=canvas.getContext('2d',{alpha:false})!;
  this.ready=Promise.all([this.load(this.bg,'/forest.png'),this.load(this.sprite,'/guardian.png')]).then(()=>{this.render()});
  this.resize=new ResizeObserver(()=>this.fit());this.resize.observe(canvas);this.fit();
  for(let i=0;i<65;i++)this.ambient.push({x:(i*173.23)%W,y:(i*79.13)%H,s:1+(i%3)*.6,phase:i*2.4});
  window.addEventListener('keydown',this.keydown);window.addEventListener('keyup',this.keyup);window.addEventListener('blur',this.blur);document.addEventListener('visibilitychange',this.visibility);
  this.raf=requestAnimationFrame(this.frame);
  const context=(document as unknown as {modelContext?:{registerTool:(t:unknown,o:unknown)=>Promise<void>}}).modelContext;
  if(context?.registerTool){try{Promise.resolve(context.registerTool({name:'read_luma_progress',description:'Read current Luma adventure progress, abilities, sunseeds, and location.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw Error('This tool takes an empty object.');return {...this.state,paused:this.paused};}},{signal:this.lifecycle.signal})).catch(()=>{})}catch{}}
 }
 private load(img:HTMLImageElement,src:string){return new Promise<void>((resolve,reject)=>{img.onload=()=>resolve();img.onerror=()=>reject(Error(`Unable to load ${src}`));img.src=src})}
 private fit(){const r=this.canvas.getBoundingClientRect(),dpr=Math.min(window.devicePixelRatio||1,2);this.canvas.width=Math.round(r.width*dpr);this.canvas.height=Math.round(r.height*dpr);this.scale=this.canvas.height/H;this.viewport=this.canvas.width/this.scale;}
 private keydown=(e:KeyboardEvent)=>{if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown','Space','KeyA','KeyD','KeyW','KeyJ','KeyX','KeyK','KeyE','ShiftLeft','ShiftRight'].includes(e.code)){if(this.started&&!this.paused){e.preventDefault();this.input(e.code,true)}}};
 private keyup=(e:KeyboardEvent)=>{this.input(e.code,false)};
 private blur=()=>{this.keys.clear();this.pressed.clear();this.accumulator=0};
 private visibility=()=>{if(document.hidden){this.blur();this.save();this.audio?.suspend()}else if(!this.paused&&!this.mute)this.audio?.resume()};
 input(key:string,down:boolean){if(down&&!this.paused){if(!this.keys.has(key))this.pressed.add(key);this.keys.add(key)}else this.keys.delete(key)}
 setPaused(value:boolean){this.paused=value;this.blur();if(value)this.audio?.suspend();else if(!this.mute)this.audio?.resume()}
 setMuted(value:boolean){this.mute=value;if(value)this.audio?.suspend();else if(!this.paused)this.audio?.resume()}
 hasSave(){try{return !!this.readSave()}catch{return false}}
 private readSave(){try{const raw=localStorage.getItem(SAVE_KEY);if(!raw)return null;const s=JSON.parse(raw);if(s.version!==1||!Number.isInteger(s.room)||s.room<0||s.room>5||!Array.isArray(s.seeds)||!s.seeds.every((x:unknown)=>typeof x==='number'&&[2,4,5].includes(x))||!Array.isArray(s.collected)||!Array.isArray(s.visited))return null;return s}catch{return null}}
 start(resume=false){
  this.world=rooms();this.collected.clear();this.broken.clear();this.particles=[];this.state={room:0,roomName:'The Waking Glade',health:5,light:0,seeds:[],dash:false,doubleJump:false,visited:[0],time:0,won:false,message:''};this.checkpoint={room:0,x:230,y:705};
  const s=resume?this.readSave():null;if(s){this.state={...this.state,room:s.room,seeds:[...new Set<number>(s.seeds)],dash:!!s.dash,doubleJump:!!s.doubleJump,light:Number.isFinite(s.light)?Math.max(0,s.light):0,visited:s.visited.filter((n:number)=>Number.isInteger(n)&&n>=0&&n<6),time:Number.isFinite(s.time)?s.time:0};this.collected=new Set(s.collected.filter((n:unknown)=>typeof n==='string'));this.broken=new Set(s.broken||[]);if(s.checkpoint&&Number.isInteger(s.checkpoint.room)&&s.checkpoint.room>=0&&s.checkpoint.room<6&&Number.isFinite(s.checkpoint.x))this.checkpoint=s.checkpoint;}
  this.player={x:s?this.checkpoint.x:230,y:705,vx:0,vy:0,face:1,grounded:true};this.state.room=s?this.checkpoint.room:0;this.state.roomName=this.world[this.state.room].name;this.safe={x:this.player.x,y:705};this.camera=Math.max(0,this.player.x-this.viewport*.35);this.invincible=0;this.attack=0;this.attackCooldown=0;this.dashTime=0;this.dashCooldown=0;this.transition=0;this.coyote=.1;this.jumpBuffer=0;this.usedDouble=false;this.started=true;this.paused=false;
  try{if(!this.audio)this.audio=new AudioContext();if(!this.mute)this.audio.resume()}catch{}
  this.toast(s?'Welcome back, little light.':'Follow the fireflies. Your adventure begins to the east.');this.save();this.publish();
 }
 save(){if(!this.started)return;try{localStorage.setItem(SAVE_KEY,JSON.stringify({version:1,room:this.state.room,checkpoint:this.checkpoint,seeds:this.state.seeds,dash:this.state.dash,doubleJump:this.state.doubleJump,light:this.state.light,visited:this.state.visited,time:this.state.time,collected:[...this.collected],broken:[...this.broken]}))}catch{this.saveAvailable=false}}
 destroy(){this.stopped=true;cancelAnimationFrame(this.raf);this.resize.disconnect();this.lifecycle.abort();window.removeEventListener('keydown',this.keydown);window.removeEventListener('keyup',this.keyup);window.removeEventListener('blur',this.blur);document.removeEventListener('visibilitychange',this.visibility);this.save();this.audio?.close()}
 private frame=(now:number)=>{if(this.stopped)return;const dt=Math.min((now-(this.last||now))/1000,.05);this.last=now;this.elapsed+=dt;if(!this.paused&&!document.hidden&&!this.state.won){this.accumulator+=dt;while(this.accumulator>=1/120){this.update(1/120);this.accumulator-=1/120}}this.render();this.raf=requestAnimationFrame(this.frame)};
 private held(...keys:string[]){return keys.some(k=>this.keys.has(k))}
 private tap(...keys:string[]){return keys.some(k=>this.pressed.has(k))}
 private update(dt:number){
  const p=this.player,r=this.world[this.state.room];this.state.time+=dt;this.invincible=Math.max(0,this.invincible-dt);this.attack=Math.max(0,this.attack-dt);this.attackCooldown=Math.max(0,this.attackCooldown-dt);this.dashTime=Math.max(0,this.dashTime-dt);this.dashCooldown=Math.max(0,this.dashCooldown-dt);this.transition=Math.max(0,this.transition-dt);this.shake=Math.max(0,this.shake-dt*25);this.jumpBuffer=Math.max(0,this.jumpBuffer-dt);this.coyote=Math.max(0,this.coyote-dt);
  if(this.state.message&&this.elapsed>this.messageUntil){this.state.message='';this.publish()}
  if(this.tap('Space','KeyW','ArrowUp'))this.jumpBuffer=.14;
  const dir=Number(this.held('KeyD','ArrowRight'))-Number(this.held('KeyA','ArrowLeft'));
  if(dir)p.face=dir;
  if(this.jumpBuffer>0&&(this.coyote>0||this.state.doubleJump&&!this.usedDouble)){
   const double=this.coyote<=0;this.usedDouble=double;p.vy=double?-690:-730;p.grounded=false;this.coyote=0;this.jumpBuffer=0;this.burst(p.x,p.y,12,double?'#d7edb7':'#e3d298');this.tone(double?740:440,.09,'sine',.05);
  }
  if(this.tap('ShiftLeft','ShiftRight','KeyK')){if(this.state.dash&&this.dashCooldown<=0){this.dashTime=.18;this.dashCooldown=.7;p.vy=0;this.invincible=Math.max(this.invincible,.23);this.burst(p.x,p.y-30,14,'#ffdaa0');this.tone(230,.15,'triangle',.07)}else if(!this.state.dash)this.toast('Find the Sun Dash in Whisper Falls.')}
  if(this.tap('KeyJ','KeyX')&&this.attackCooldown<=0){this.attack=.21;this.attackCooldown=.31;this.tone(510,.09,'triangle',.06);for(const e of r.enemies){if(e.hp>0&&Math.abs(e.x-p.x)<140&&Math.abs(e.y-(p.y-35))<100&&(e.x-p.x)*p.face>-25){e.hp--;e.hit=.25;this.shake=3;this.burst(e.x,e.y,20,'#ffe8a4');if(e.hp<=0){this.state.light+=3;this.tone(880,.16,'sine',.05);this.publish()}}}}
  const target=dir*325;p.vx=this.dashTime>0?p.face*1000:p.vx+(target-p.vx)*Math.min(1,dt*(dir?15:20));
  const oldY=p.y,oldX=p.x;p.x+=p.vx*dt;
  if(this.dashTime<=0){const gravity=p.vy<0&&!this.held('Space','KeyW','ArrowUp')?2300:1550;p.vy=Math.min(1000,p.vy+gravity*dt)}
  p.y+=p.vy*dt;p.grounded=false;
  for(const plat of r.platforms){if(p.x+18>plat.x&&p.x-18<plat.x+plat.w&&p.vy>=0&&oldY<=plat.y+2&&p.y>=plat.y){p.y=plat.y;p.vy=0;p.grounded=true;this.coyote=.12;this.usedDouble=false;if(plat.y===705){this.safe={x:p.x,y:p.y}}}}
  if(this.state.room===2&&!this.broken.has(2)&&p.x+18>590&&p.x-18<635&&p.y>430){if(this.dashTime>0){this.broken.add(2);this.burst(612,580,55,'#ffc478');this.shake=8;this.toast('A new path opens. Keep growing, little light.');this.save()}else{p.x=oldX<610?571:654;p.vx=0;if(this.tap('KeyE','ArrowDown'))this.toast('Amber thorns yield to Sun Dash. Press Shift.')}}
  p.x=Math.max(25,Math.min(W-25,p.x));
  if(p.y>H+130){this.hurt(true);this.pressed.clear();return}
  for(const e of r.enemies){if(e.hp<=0)continue;e.hit=Math.max(0,e.hit-dt);e.phase+=dt*.8;e.x=e.home+Math.sin(e.phase)*e.range;const ey=e.y+Math.sin(e.phase*3)*9;if(Math.abs(e.x-p.x)<39&&Math.abs(ey-(p.y-35))<48&&this.dashTime<=0)this.hurt(false);}
  for(const m of r.motes){if(!this.collected.has(m.id)&&Math.hypot(m.x-p.x,m.y-(p.y-35))<44){this.collected.add(m.id);this.state.light++;this.burst(m.x,m.y,8,'#fff0a3');this.tone(750+(this.state.light%5)*90,.09,'sine',.027);this.publish()}}
  if(r.ability&&!this.state[r.ability.type]&&Math.hypot(r.ability.x-p.x,r.ability.y-(p.y-35))<72){this.state[r.ability.type]=true;this.burst(r.ability.x,r.ability.y,65,'#f8e3a8');this.toast(r.ability.type==='dash'?'Sun Dash awakened! Press Shift to burst through amber thorns.':'Sky Feather awakened! Press jump again in the air.');this.chime();this.save();this.publish()}
  if(r.seed&&!this.state.seeds.includes(this.state.room)&&Math.hypot(r.seed.x-p.x,r.seed.y-(p.y-35))<65){const guardian=r.enemies.some(e=>e.hp>0&&Math.hypot(e.x-r.seed!.x,e.y-r.seed!.y)<220);if(!guardian){this.state.seeds.push(this.state.room);this.burst(r.seed.x,r.seed.y,90,'#ffdd78');this.toast(`Sunseed ${this.state.seeds.length} of 3 found. The forest feels a little brighter.`);this.chime();this.save();this.publish()}else if(this.tap('KeyE','ArrowDown'))this.toast('Free the sunseed from the shadow wisp. Press J to strike.')}
  if(this.tap('KeyE','ArrowDown')){
   let used=false;
   if(r.shrine!==undefined&&Math.abs(r.shrine-p.x)<100&&Math.abs(p.y-705)<90){used=true;this.state.health=5;this.checkpoint={room:this.state.room,x:r.shrine,y:705};this.burst(p.x,p.y-30,35,'#acffce');if(this.state.room===0&&this.state.seeds.length===3){this.state.won=true;this.chime();this.toast('The Sunwell is awake. Thank you, little guardian.')}else this.toast(this.saveAvailable?'Hearts restored. Your journey is saved.':'Hearts restored. Browser storage is unavailable.');this.save();this.publish()}
   if(!used){for(const door of r.doors){if(Math.abs(door.x-p.x)<105&&Math.abs(p.y-door.y)<100){used=true;if(door.needs&&!this.state[door.needs])this.toast('A Sky Feather will carry you to this hidden path.');else this.enter(door.to);break}}
   }
   if(!used&&this.state.room===0&&this.state.seeds.length<3&&p.x<350)this.toast('Bring three sunseeds to the Sunwell to awaken the forest.');
  }
  for(const q of this.particles){q.life-=dt;q.x+=q.vx*dt;q.y+=q.vy*dt;q.vy+=100*dt}this.particles=this.particles.filter(q=>q.life>0);
  if(this.dashTime>0)this.particles.push({x:p.x,y:p.y-30,vx:-p.face*35,vy:0,life:.3,max:.3,color:'#ffe6a1',r:18});
  this.camera+=(Math.max(0,Math.min(W-this.viewport,p.x-this.viewport*.4))-this.camera)*Math.min(1,dt*5);
  if(this.elapsed>this.nextNote){const notes=[261.63,329.63,392,523.25,440,392,329.63,293.66];this.tone(notes[this.music++%notes.length],1.7,'sine',.014);this.nextNote=this.elapsed+1.4}
  if(this.state.time-this.lastPublish>1){this.lastPublish=this.state.time;this.publish()}
  this.pressed.clear();
 }
 private enter(to:number){const previous=this.state.room,r=this.world[to],back=r.doors.find(d=>d.to===previous);this.state.room=to;this.state.roomName=r.name;if(!this.state.visited.includes(to))this.state.visited.push(to);this.player={x:back?back.x+(back.x<300?105:back.x>2100?-105:0):300,y:back?back.y:705,vx:0,vy:0,face:back&&back.x>2100?-1:1,grounded:true};this.safe={x:r.shrine??310,y:705};this.invincible=1;this.camera=Math.max(0,Math.min(W-this.viewport,this.player.x-this.viewport*.4));this.transition=.6;this.checkpoint={room:to,x:r.shrine??(back&&back.x>2100?2100:300),y:705};this.save();this.publish();this.tone(330,.4,'sine',.03)}
 private hurt(fall:boolean){if(this.invincible>0&&!fall)return;this.state.health--;this.invincible=1.6;this.shake=6;this.burst(this.player.x,this.player.y-25,22,'#ffb991');this.tone(130,.18,'triangle',.06);if(this.state.health<=0){this.state.health=5;this.state.room=this.checkpoint.room;this.state.roomName=this.world[this.state.room].name;this.player.x=this.checkpoint.x;this.player.y=705;this.toast('A little rest, a little courage. Your light is safe.')}else if(fall){this.player.x=this.safe.x;this.player.y=this.safe.y;this.toast('The forest caught you. Try another leap.')}else{this.player.vx=-this.player.face*240;this.player.vy=-220}this.player.vy=fall?0:this.player.vy;this.dashTime=0;this.publish()}
 private toast(message:string){this.state.message=message;this.messageUntil=this.elapsed+5.5;this.publish()}
 private publish(){this.onUpdate({...this.state,seeds:[...this.state.seeds],visited:[...this.state.visited]})}
 private burst(x:number,y:number,n:number,color:string){for(let i=0;i<n;i++){const a=Math.random()*Math.PI*2,s=30+Math.random()*190,l=.3+Math.random()*.65;this.particles.push({x,y,vx:Math.cos(a)*s,vy:Math.sin(a)*s,life:l,max:l,color,r:1+Math.random()*4})}}
 private tone(freq:number,duration:number,type:OscillatorType='sine',volume=.04){if(!this.audio||this.mute||this.audio.state!=='running')return;const o=this.audio.createOscillator(),g=this.audio.createGain(),t=this.audio.currentTime;o.type=type;o.frequency.setValueAtTime(freq,t);g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(volume,t+.02);g.gain.exponentialRampToValueAtTime(.0001,t+duration);o.connect(g);g.connect(this.audio.destination);o.start(t);o.stop(t+duration+.03)}
 private chime(){[523,659,784,1046].forEach((f,i)=>{setTimeout(()=>{if(!this.stopped)this.tone(f,.55,'sine',.05)},i*110)})}
 private glow(x:number,y:number,r:number,color:string){const c=this.ctx,g=c.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'transparent');c.fillStyle=g;c.fillRect(x-r,y-r,r*2,r*2)}
 private label(text:string,x:number,y:number,color='#f8e8b8',size=15){const c=this.ctx;c.font=`${size}px Georgia`;c.textAlign='center';c.fillStyle='rgba(3,24,22,.72)';const w=c.measureText(text).width+24;c.beginPath();c.roundRect(x-w/2,y-17,w,28,5);c.fill();c.fillStyle=color;c.fillText(text,x,y+2)}
 private render(){
  const c=this.ctx;if(!this.scale)return;c.setTransform(this.scale,0,0,this.scale,0,0);c.clearRect(0,0,this.viewport,H);const r=this.world[this.state.room],p=this.player,t=this.elapsed;
  if(this.bg.complete&&this.bg.naturalWidth){const baseWidth=Math.max(this.viewport+180,1450),baseHeight=baseWidth/1.5;const offset=this.started?this.camera*.075:70; c.drawImage(this.bg,-offset,-(baseHeight-H)*.32,baseWidth,baseHeight)}else{c.fillStyle='#184e40';c.fillRect(0,0,this.viewport,H)}
  c.fillStyle=r.tint;c.fillRect(0,0,this.viewport,H);
  const shade=c.createLinearGradient(0,0,0,H);shade.addColorStop(0,'#06232144');shade.addColorStop(.5,'#06232100');shade.addColorStop(1,'#07292388');c.fillStyle=shade;c.fillRect(0,0,this.viewport,H);
  if(!this.started){for(const a of this.ambient){const x=(a.x+t*7)%(this.viewport+50)-25,y=a.y+Math.sin(t+a.phase)*15;this.glow(x,y,13,'#faff9a20');c.fillStyle='#fffacbb0';c.beginPath();c.arc(x,y,a.s,0,Math.PI*2);c.fill()}return}
  c.save();c.translate(-this.camera+(Math.random()-.5)*this.shake,(Math.random()-.5)*this.shake);
  for(const plat of r.platforms){if(plat.x+plat.w<this.camera-50||plat.x>this.camera+this.viewport+50)continue;c.save();c.beginPath();c.moveTo(plat.x,plat.y+6);c.lineTo(plat.x+10,plat.y);c.lineTo(plat.x+plat.w-9,plat.y);c.lineTo(plat.x+plat.w,plat.y+8);c.lineTo(plat.x+plat.w-6,plat.y+plat.h*.8);c.lineTo(plat.x+plat.w*.78,plat.y+plat.h);c.lineTo(plat.x+plat.w*.43,plat.y+plat.h*.87);c.lineTo(plat.x+12,plat.y+plat.h);c.closePath();c.clip();if(this.bg.naturalWidth)c.drawImage(this.bg,120,760,980,170,plat.x,plat.y,plat.w,plat.h);else{c.fillStyle='#314b34';c.fillRect(plat.x,plat.y,plat.w,plat.h)}const dark=c.createLinearGradient(0,plat.y,0,plat.y+plat.h);dark.addColorStop(0,'#273d1900');dark.addColorStop(1,'#031c21dd');c.fillStyle=dark;c.fillRect(plat.x,plat.y,plat.w,plat.h);c.fillStyle='#acbc6155';c.fillRect(plat.x,plat.y,plat.w,4);c.restore();}
  if(this.state.room===2&&!this.broken.has(2)){this.glow(612,580,105,'#ffac4933');c.fillStyle='#86682caf';c.fillRect(590,435,45,270);c.strokeStyle='#ffc177';c.lineWidth=3;for(let i=0;i<7;i++){c.beginPath();c.moveTo(580,455+i*36);c.lineTo(639,478+i*32);c.lineTo(594,495+i*29);c.stroke()}this.label('AMBER THORNS',612,411,'#ffd797',12);if(Math.abs(p.x-612)<160)this.label('SHIFT · Sun Dash',612,745)}
  for(const door of r.doors){this.glow(door.x,door.y-55,70,door.needs&&!this.state[door.needs]?'#98b2d51a':'#dfecae25');c.save();c.strokeStyle='#e2d5a777';c.lineWidth=2;c.beginPath();c.ellipse(door.x,door.y-44,25,45,0,Math.PI,Math.PI*2);c.stroke();c.restore();const close=Math.abs(p.x-door.x)<105&&Math.abs(p.y-door.y)<100;this.label(close?'E · '+door.label:door.label,door.x,door.y-105,close?'#fff0b0':'#d6e4cf',close?15:13)}
  if(r.shrine!==undefined){const x=r.shrine;this.glow(x,657,100,'#b3ffd23a');c.strokeStyle='#baeed3';c.lineWidth=3;c.beginPath();c.ellipse(x,672,22,9,0,0,Math.PI*2);c.stroke();c.beginPath();c.moveTo(x,660);c.lineTo(x-12,645);c.lineTo(x,625);c.lineTo(x+12,645);c.closePath();c.fillStyle='#cdf7cb';c.shadowBlur=20;c.shadowColor='#dcffb9';c.fill();c.shadowBlur=0;if(Math.abs(p.x-x)<105)this.label(this.state.room===0&&this.state.seeds.length===3?'E · Restore the Sunwell':'E · Rest at the Sunwell',x,598)}
  for(const m of r.motes){if(this.collected.has(m.id))continue;const y=m.y+Math.sin(t*2+m.x)*5;this.glow(m.x,y,20,'#ffe68844');c.fillStyle='#ffe9a8';c.save();c.translate(m.x,y);c.rotate(Math.PI/4);c.fillRect(-3.5,-3.5,7,7);c.restore()}
  if(r.ability&&!this.state[r.ability.type]){const a=r.ability,y=a.y+Math.sin(t*2)*7;this.glow(a.x,y,80,'#fff1b14f');c.save();c.translate(a.x,y);c.rotate(t*.25);c.strokeStyle='#ffecc0';c.lineWidth=2;c.strokeRect(-20,-20,40,40);c.restore();c.fillStyle='#fff3ca';c.font='32px Georgia';c.textAlign='center';c.fillText(a.type==='dash'?'ϟ':'✧',a.x,y+11);this.label(a.type==='dash'?'SUN DASH':'SKY FEATHER',a.x,y-48,'#ffedb5',13)}
  if(r.seed&&!this.state.seeds.includes(this.state.room)){const {x,y}=r.seed;this.glow(x,y,100,'#ffcf6455');c.save();c.translate(x,y+Math.sin(t*2)*6);c.rotate(Math.sin(t)*.15);c.beginPath();c.moveTo(0,-23);c.bezierCurveTo(31,2,18,23,0,23);c.bezierCurveTo(-18,23,-31,2,0,-23);const g=c.createLinearGradient(-15,-20,15,22);g.addColorStop(0,'#fff2b6');g.addColorStop(1,'#ecab4d');c.fillStyle=g;c.shadowColor='#ffd56c';c.shadowBlur=22;c.fill();c.restore();this.label('SUNSEED',x,y-48,'#ffdf8d',12)}
  for(const e of r.enemies){if(e.hp<=0)continue;const y=e.y+Math.sin(e.phase*3)*9,large=this.state.room===5&&e.home===1840;this.glow(e.x,y,large?66:46,e.hit>0?'#ffe5aa66':'#bd86e74d');c.fillStyle=e.hit>0?'#f3d8bf':'#483752';c.beginPath();c.arc(e.x,y,large?27:20,0,Math.PI*2);c.fill();c.strokeStyle='#c3a5d7';c.lineWidth=2;c.stroke();c.fillStyle='#ffd4a0';c.beginPath();c.arc(e.x-7,y-3,3,0,Math.PI*2);c.arc(e.x+7,y-3,3,0,Math.PI*2);c.fill();if(large){this.label('THE DROWSY KEEPER',e.x,y-51,'#e9d4ed',12);c.fillStyle='#a881ae';c.fillRect(e.x-28,y+40,56*(e.hp/5),3)}}
  c.fillStyle='#031c2166';c.beginPath();c.ellipse(p.x,p.y+3,33,8,0,0,Math.PI*2);c.fill();this.glow(p.x,p.y-35,70,'#ffebb21a');
  c.save();c.translate(p.x,p.y);if(this.invincible>0&&Math.floor(t*13)%2===0)c.globalAlpha=.5;c.scale(p.face,1);const moving=Math.abs(p.vx)>35&&p.grounded,bob=moving?Math.sin(t*17)*3:Math.sin(t*2)*1.5;const squash=this.dashTime>0?1.16:1; c.scale(squash,1/squash);if(this.sprite.naturalWidth)c.drawImage(this.sprite,-45,-96+bob,87,96);c.restore();
  if(this.attack>0){c.save();c.translate(p.x,p.y-40);c.scale(p.face,1);c.strokeStyle='#fff2c6';c.shadowColor='#ffdd86';c.shadowBlur=22;c.lineWidth=7;c.beginPath();const phase=(.21-this.attack)/.21;c.arc(20,0,83,-1.2+phase*.3,1.2+phase*.3);c.stroke();c.restore()}
  for(const q of this.particles){c.globalAlpha=q.life/q.max;this.glow(q.x,q.y,q.r*2,q.color+'44');c.fillStyle=q.color;c.beginPath();c.arc(q.x,q.y,q.r*q.life/q.max,0,Math.PI*2);c.fill()}c.globalAlpha=1;
  for(const a of this.ambient){const x=(a.x+t*5)%W,y=a.y+Math.sin(t*.6+a.phase)*15;this.glow(x,y,12,'#fbffb223');c.globalAlpha=.3+(Math.sin(t+a.phase)+1)*.25;c.fillStyle='#fff5be';c.beginPath();c.arc(x,y,a.s,0,Math.PI*2);c.fill()}c.globalAlpha=1;c.restore();
  if(this.transition>0){c.fillStyle=`rgba(252,239,200,${this.transition*.6})`;c.fillRect(0,0,this.viewport,H)}
 }
}
