"use client";
import { useEffect, useRef, useState } from 'react';
import { ArrowLeft, ArrowRight, AudioLines, BookOpen, Check, ChevronRight, Compass, Expand, Feather, Heart, Leaf, Map, Pause, Play, RotateCcw, Settings2, Sparkles, Sun, Volume2, VolumeX, X, Zap } from 'lucide-react';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import type { Game, Snapshot } from './game';
const initial: Snapshot = {room:0, roomName:'The Waking Glade', health:5, light:0, seeds:[], dash:false, doubleJump:false, visited:[0], time:0, won:false, message:''};
const roomNames=['Waking Glade','Whisper Falls','Amber Hollow','Windborne Canopy','Moonpetal Sanctuary','Sunspire Ruins'];
export default function Home(){
 const canvas=useRef<HTMLCanvasElement>(null), game=useRef<Game|null>(null);
 const [state,setState]=useState(initial),[ready,setReady]=useState(false),[playing,setPlaying]=useState(false),[panel,setPanel]=useState<'map'|'guide'|'pause'|null>(null),[muted,setMuted]=useState(false),[saved,setSaved]=useState(false),[error,setError]=useState('');
 useEffect(()=>{let dead=false; import('./game').then(({Game})=>{if(dead||!canvas.current)return;const g=new Game(canvas.current,s=>setState({...s}));game.current=g;g.ready.then(()=>{if(!dead)setReady(true)}).catch(()=>setError('The forest could not load. Refresh to try again.'));setSaved(g.hasSave());});return()=>{dead=true;game.current?.destroy();game.current=null};},[]);
 useEffect(()=>{game.current?.setPaused(!playing||panel!==null)},[playing,panel]);
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.code==='Escape'&&playing)setPanel(p=>p?null:'pause');if(e.code==='KeyM'&&playing){e.preventDefault();setPanel(p=>p==='map'?null:'map')}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[playing]);
 const start=(resume=false)=>{game.current?.start(resume);setPlaying(true);setPanel(null);};
 const mute=()=>{setMuted(!muted);game.current?.setMuted(!muted)};
 const press=(key:string,down:boolean)=>game.current?.input(key,down);
 const objective=state.won?'The forest is singing again.':!state.dash?'Follow the light to Whisper Falls.':!state.doubleJump?'Dash through the amber thorns in Amber Hollow.':state.seeds.length<3?'Find the three lost sunseeds.':'Return to the Sunwell in the Waking Glade.';
 return <main className="app-shell">
  <header className="topbar"><a className="brand" href="/" aria-label="Luma home"><span className="brand-icon"><Sun size={23}/></span><span>LUMA<span className="brand-sub">THE SUNSEED</span></span></a><div className="chapter"><span className="chapter-line"/> A LITTLE LIGHT. A BIG ADVENTURE. <span className="chapter-line"/></div><div className="header-actions"><span className="local-save"><span/> SAVED ON THIS DEVICE</span><button className="icon-button" onClick={()=>setPanel('guide')} aria-label="How to play"><BookOpen size={19}/></button><button className="icon-button" onClick={mute} aria-label={muted?'Enable sound':'Mute sound'}>{muted?<VolumeX size={19}/>:<Volume2 size={19}/>}</button></div></header>
  <section className="game-frame" aria-label="Luma game">
   <canvas ref={canvas} aria-label="Forest adventure. Use arrows or A D to move, Space to jump, J to attack, Shift to dash, E to interact, M for map." tabIndex={0}/>
   <div className="vignette"/>
   {playing&&<><div className="hud"><div className="vitality"><div className="heart-row">{[0,1,2,3,4].map(n=><Heart key={n} size={22} fill={n<state.health?'currentColor':'none'} className={n<state.health?'':'empty-heart'}/>)}</div><div className="hud-resources"><span><Sparkles size={15}/>{String(state.light).padStart(2,'0')}</span><i/><span><Sun size={16}/>{state.seeds.length} / 3</span></div></div><div className="location"><span>THE VERDANT WILDS</span><h2>{state.roomName}</h2></div><button className="glass-button" aria-label="Pause game" onClick={()=>setPanel('pause')}><Pause size={20}/></button></div><div className="quest"><span className="quest-icon"><Sun size={20}/></span><div><small>LET THE FOREST BLOOM</small><p>{objective}</p></div></div><button className="map-button" onClick={()=>setPanel('map')}><Map size={17}/> World map <kbd>M</kbd></button><div className="abilities"><span title="Jump"><Feather size={20}/><kbd>SPACE</kbd></span><span className={state.dash?'':'locked'} title={state.dash?'Sun dash':'Dash not yet found'}><Zap size={20}/><kbd>SHIFT</kbd></span><span className={state.doubleJump?'':'locked'} title={state.doubleJump?'Double jump':'Double jump not yet found'}><Sparkles size={20}/><kbd>2× SPACE</kbd></span></div>{state.message&&<div className="game-toast" key={state.message}><Sparkles size={18}/>{state.message}</div>}</>}
   {!playing&&<div className="title-screen"><div className="eyebrow"><span/> AN ADVENTURE WORTH GETTING LOST IN <span/></div><h1>Luma<span>THE SUNSEED</span></h1><p>A little guardian. A world waiting to bloom.</p><button className="begin-button" disabled={!ready} onClick={()=>start(saved)}><Play size={18} fill="currentColor"/>{error||(!ready?'Awakening the forest…':saved?'Continue your journey':'Begin your journey')}<ChevronRight size={19}/></button>{saved&&<button className="text-button" onClick={()=>start(false)}>Start a new journey</button>}<div className="start-hint"><span><HeadphoneIcon/> Best with headphones</span><i/><span><Compass size={14}/> Explore at your own pace</span></div></div>}
   {playing&&state.won&&<div className="victory"><Sun size={42}/><span>EVERY LITTLE LIGHT MATTERS</span><h2>You made the world bloom.</h2><p>Three sunseeds. One brave little guardian.<br/>The wilds are full of wonder again.</p><button className="begin-button" onClick={()=>start(false)}><RotateCcw size={18}/>A new adventure</button></div>}
   <div className="touch-controls">{['ArrowLeft','ArrowRight','Space','KeyJ','ShiftLeft','KeyE'].map((key,i)=><button key={key} aria-label={['Move left','Move right','Jump','Attack','Dash','Interact'][i]} onPointerDown={e=>{e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);press(key,true)}} onPointerUp={()=>press(key,false)} onPointerCancel={()=>press(key,false)}>{['◀','▶','↑','✦','ϟ','E'][i]}</button>)}</div>
  </section>
  <footer className="game-footer"><div className="control-group"><span><kbd>A</kbd><kbd>D</kbd> Move</span><span><kbd>SPACE</kbd> Jump</span><span><kbd>J</kbd> Light strike</span><span><kbd>E</kbd> Interact</span></div><div className="footer-right"><span className="genre">EXPLORE. GROW. GLOW.</span><button onClick={()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen().catch(()=>{});}} aria-label="Toggle fullscreen"><Expand size={17}/></button></div></footer>
  <Dialog open={panel!==null} onOpenChange={v=>!v&&setPanel(null)}><DialogContent className="game-dialog"><DialogTitle>{panel==='map'?'The Verdant Wilds':panel==='guide'?'A little guidance':'Take a little breath'}</DialogTitle><DialogDescription>{panel==='map'?'A world that opens as you grow.':panel==='guide'?'Follow your curiosity. Bring the sunseeds home.':'Your adventure will be right here.'}</DialogDescription>{panel==='map'?<><div className="world-map">{[4,3,5,0,1,2].map(n=><div key={n} className={`map-room room-${n} ${state.visited.includes(n)?'discovered':''} ${n===state.room?'current':''}`}><span>{n===state.room?<Leaf size={20}/>:state.seeds.includes(n)?<Check size={20}/>:<Compass size={20}/>}</span><strong>{state.visited.includes(n)?roomNames[n]:'Unexplored'}</strong>{n===state.room&&<small>YOU ARE HERE</small>}</div>)}</div><p className="map-note">Passages connect the marked clearings. Find Sun Dash in the falls, then the Sky Feather beyond the amber thorns.</p></>:panel==='guide'?<div className="guide"><p>You are Luma, keeper of a sleepy forest. Recover three sunseeds and return them to the Sunwell where your journey began.</p><div className="guide-grid">{[['A / D or ← →','Move'],['Space / W / ↑','Jump · hold for height'],['J / X','Light strike'],['Shift / K','Sun Dash · once discovered'],['Space in midair','Double jump · once discovered'],['E / ↓','Use shrines and passages'],['M','Open the world map'],['Esc','Pause your adventure']].map(([a,b])=><div key={a}><kbd>{a}</kbd><span>{b}</span></div>)}</div><p className="map-note">Glowing shrines restore hearts and save your journey on this device. Falling returns you to safe ground. New abilities open paths you passed before.</p></div>:<div className="pause-actions"><button className="begin-button" onClick={()=>setPanel(null)}><Play size={17}/>Back to the forest</button><button onClick={()=>setPanel('guide')}><BookOpen size={17}/>How to play</button><button onClick={()=>setPanel('map')}><Map size={17}/>World map</button><button onClick={mute}>{muted?<VolumeX size={17}/>:<Volume2 size={17}/>}Sound {muted?'off':'on'}</button><button onClick={()=>{game.current?.save();setPlaying(false);setSaved(true);setPanel(null)}}>Save & return to title</button></div>}</DialogContent></Dialog>
 </main>
}
function HeadphoneIcon(){return <AudioLines size={15}/>}
